openapi: 3.0.0
info:
  version: 1.0.0
  title: playlists
  description: music player
paths: {}
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/BogdanKalysh/Max_music/1.0.0